service: leetcode-lambda-functions

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

functions:
  mergeStringsAlternately:
    handler: dist/13_08_2024/mergeStringsAlternately.handler
    events:
      - http:
          path: merge-strings-alternately
          method: post
  gcdOfStrings:
    handler: dist/14_08_2024/gcdOfStrings.handler
    events:
      - http:
          path: gcd-of-strings
          method: post
  

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3024
